services:
  - type: web
    name: microgrid-backend
    env: python
    buildCommand: |
      chmod +x ./setup.sh
      ./setup.sh
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: DATABASE_URL
        value: "sqlite:///tmp/sql_app.db"
    plan: free
