services:
  - type: web
    name: microgrid-backend
    env: python
    python:
      version: "3.10.13"
    buildCommand: |
      pip install --upgrade pip && \
      pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: DATABASE_URL
        fromDatabase:
          name: microgrid-db
          property: connectionString
      - key: ENVIRONMENT
        value: "production"
    plan: free

databases:
  - name: microgrid-db
    databaseName: microgrid
    user: microgrid
    plan: free
